service: backend

# Definicion de la plataforma
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: dev

# Plugin necesario para AppSync: serverless-appsync-plugin
# https://github.com/sid88in/serverless-appsync-plugin
plugins:
   - serverless-appsync-plugin

custom:
  appSync:
    name: youtubeAppSyncApi
    authenticationType: AMAZON_COGNITO_USER_POOLS
    additionalAuthenticationProviders:
      - authenticationType: AWS_IAM
    # Se especifica la configuración de un grupo de usuarios de Cognito que se utilizará para autenticar a los usuarios de la aplicación de AppSync 
    # y controlar quién tiene acceso a qué recursos y operaciones.
    userPoolConfig:
      awsRegion: us-west-1
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool
    # mappingTemplates se utiliza para especificar qué plantillas VTL se utilizarán para procesar diferentes tipos de solicitudes GraphQL y cómo se obtienen o 
    # modifican los datos en el backend de la aplicacion
    mappingTemplatesLocation: mapping-templates
    mappingTemplates: 
      - type: Query 
        field: getBookById
        dataSource: booksTable
      - type: Query 
        field: listBooks
        dataSource: booksTable
      - type: Mutation 
        field: createBook
        dataSource: booksTable
    dataSources:
      - type: AMAZON_DYNAMODB
        name: booksTable
        config: 
          tableName: !Ref booksTable

# Forma de vincular otro yml ${file(nombre.yml)}
resources:
 Resources:
  ${file(resources.yml)}
